function diffs_evaluated = diffs_bellman_optimal(in1)
%DIFFS_BELLMAN_OPTIMAL
%    DIFFS_EVALUATED = DIFFS_BELLMAN_OPTIMAL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025/12/02 20:53:02

V__v1_0__ = in1(:,1);
V__v1_1__ = in1(:,5);
V__v1_2__ = in1(:,9);
V__v1_3__ = in1(:,13);
V__v1_4__ = in1(:,17);
V__v1_0__ps2_1__ = in1(:,2);
V__v1_0__ps3_1__ = in1(:,3);
V__v1_1__ps2_1__ = in1(:,6);
V__v1_1__ps3_1__ = in1(:,7);
V__v1_2__ps2_1__ = in1(:,10);
V__v1_2__ps3_1__ = in1(:,11);
V__v1_3__ps2_1__ = in1(:,14);
V__v1_3__ps3_1__ = in1(:,15);
V__v1_4__ps2_1__ = in1(:,18);
V__v1_4__ps3_1__ = in1(:,19);
V__v1_0__ps2_1__ps3_1__ = in1(:,4);
V__v1_1__ps2_1__ps3_1__ = in1(:,8);
V__v1_2__ps2_1__ps3_1__ = in1(:,12);
V__v1_3__ps2_1__ps3_1__ = in1(:,16);
V__v1_4__ps2_1__ps3_1__ = in1(:,20);
diffs_evaluated = [V__v1_0__+1.0e+2;V__v1_0__ps2_1__-3.38e+3;V__v1_0__ps3_1__-5.11e+3;V__v1_0__ps2_1__ps3_1__-5.01e+3;V__v1_1__+1.0e+2;V__v1_1__ps2_1__+2.0e+2;V__v1_1__ps3_1__+1.5e+2;V__v1_1__ps2_1__ps3_1__+2.5e+2;V__v1_2__+1.0e+2;V__v1_2__ps2_1__+2.0e+2;V__v1_2__ps3_1__+1.5e+2;V__v1_2__ps2_1__ps3_1__+2.5e+2;V__v1_3__+1.0e+2;V__v1_3__ps2_1__+2.0e+2;V__v1_3__ps3_1__+1.5e+2;V__v1_3__ps2_1__ps3_1__+2.5e+2;V__v1_4__+1.0e+2;V__v1_4__ps2_1__+2.0e+2;V__v1_4__ps3_1__+1.5e+2;V__v1_4__ps2_1__ps3_1__+2.5e+2];
end
