function diff_exprs_evaluated = diff_exprs_func_state_value(in1)
%DIFF_EXPRS_FUNC_STATE_VALUE
%    DIFF_EXPRS_EVALUATED = DIFF_EXPRS_FUNC_STATE_VALUE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025/04/09 20:54:36

V__v1_0__ = in1(:,1);
V__v1_1__ = in1(:,5);
V__v1_2__ = in1(:,9);
V__v1_3__ = in1(:,13);
V__v1_4__ = in1(:,17);
V__v1_0__ps2_1__ = in1(:,2);
V__v1_0__ps3_1__ = in1(:,3);
V__v1_1__ps2_1__ = in1(:,6);
V__v1_1__ps3_1__ = in1(:,7);
V__v1_2__ps2_1__ = in1(:,10);
V__v1_2__ps3_1__ = in1(:,11);
V__v1_3__ps2_1__ = in1(:,14);
V__v1_3__ps3_1__ = in1(:,15);
V__v1_4__ps2_1__ = in1(:,18);
V__v1_4__ps3_1__ = in1(:,19);
V__v1_0__ps2_1__ps3_1__ = in1(:,4);
V__v1_1__ps2_1__ps3_1__ = in1(:,8);
V__v1_2__ps2_1__ps3_1__ = in1(:,12);
V__v1_3__ps2_1__ps3_1__ = in1(:,16);
V__v1_4__ps2_1__ps3_1__ = in1(:,20);
t2 = V__v1_2__.*9.0;
t3 = V__v1_4__.*9.0;
t4 = V__v1_0__ps2_1__.*9.0;
t5 = V__v1_0__ps3_1__.*9.0;
t6 = V__v1_2__ps3_1__.*9.0;
t7 = V__v1_4__ps2_1__.*9.0;
t8 = V__v1_0__ps2_1__ps3_1__.*9.0;
t9 = V__v1_2__+4.0e+3;
t10 = V__v1_2__ps3_1__+4.0e+3;
t11 = V__v1_2__.*(9.0./2.0e+1);
t12 = V__v1_4__.*(9.0./2.0e+1);
t13 = V__v1_0__.*(9.0./4.0e+1);
t14 = V__v1_2__.*(9.0./4.0e+1);
t15 = V__v1_4__.*(9.0./4.0e+1);
t16 = V__v1_0__.*(3.1e+1./4.0e+1);
t17 = V__v1_0__ps2_1__.*(9.0./2.0e+1);
t18 = V__v1_0__ps2_1__.*(1.1e+1./2.0e+1);
t19 = V__v1_0__ps3_1__.*(9.0./2.0e+1);
t20 = V__v1_0__ps3_1__.*(1.1e+1./2.0e+1);
t21 = V__v1_0__ps2_1__.*(9.0./4.0e+1);
t22 = V__v1_0__ps3_1__.*(9.0./4.0e+1);
t23 = V__v1_2__ps3_1__.*(9.0./1.0e+1);
t24 = V__v1_2__ps3_1__.*(9.0./2.0e+1);
t25 = V__v1_2__ps3_1__.*(9.0./4.0e+1);
t26 = V__v1_4__ps2_1__.*(9.0./1.0e+1);
t27 = V__v1_4__ps2_1__.*(9.0./2.0e+1);
t28 = V__v1_4__ps2_1__.*(9.0./4.0e+1);
t29 = V__v1_0__ps2_1__ps3_1__.*(9.0./2.0e+1);
t30 = V__v1_0__ps2_1__ps3_1__.*(9.0./4.0e+1);
t31 = V__v1_1__ps2_1__ps3_1__.*(9.0./2.0e+1);
t32 = V__v1_2__ps2_1__ps3_1__.*(9.0./2.0e+1);
t33 = V__v1_3__ps2_1__ps3_1__.*(9.0./2.0e+1);
t34 = (t9 == V__v1_0__ps2_1__);
t35 = (t10 == V__v1_0__ps2_1__ps3_1__);
t36 = (V__v1_0__ps2_1__ <= t9);
t37 = (t9 <= V__v1_0__ps2_1__);
t38 = (t10 <= V__v1_0__ps2_1__ps3_1__);
t39 = -t11;
t40 = -t12;
t41 = -t13;
t42 = -t14;
t43 = -t15;
t44 = -t17;
t45 = -t19;
t46 = -t21;
t47 = -t22;
t48 = -t23;
t49 = -t24;
t50 = -t25;
t51 = -t26;
t52 = -t27;
t53 = -t28;
t54 = -t29;
t55 = -t30;
t56 = -t31;
t57 = -t32;
t58 = -t33;
t59 = t7+1.9e+4;
t60 = t2+3.6e+4;
t61 = t6+3.6e+4;
t62 = t3+5.5e+4;
t63 = t59+3.6e+4;
t64 = (t6 == t59);
t65 = (t60 == t4);
t66 = (t62 == t5);
t68 = (t59 <= t6);
t69 = (t6 <= t59);
t70 = (t60 <= t4);
t71 = (t4 <= t60);
t72 = (t62 <= t5);
t73 = (t5 <= t62);
t74 = (t61 <= t8);
t75 = (t8 <= t61);
t78 = t18+t54+1.6e+2;
t79 = V__v1_1__ps2_1__+t44+t54+1.6e+2;
t80 = t20+t49-1.595e+3;
t81 = t18+t49-1.64e+3;
t82 = t20+t52-2.545e+3;
t83 = t18+t52-2.59e+3;
t84 = V__v1_1__ps3_1__+t45+t49-1.595e+3;
t85 = V__v1_1__ps2_1__+t44+t49-1.64e+3;
t86 = V__v1_1__ps3_1__+t45+t52-2.545e+3;
t87 = V__v1_1__ps2_1__+t44+t52-2.59e+3;
t67 = (t63 == t8);
t76 = (t63 <= t8);
t77 = (t8 <= t63);
if ~all(cellfun(@isscalar,{t68,t69,t70,t71,t72,t73,t74,t75,t76,t77}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (((t70 & t72) & t74) & t76)
    t0 = t16+t46+t47+t55+1.55e+2;
elseif (((t68 & t70) & t72) & t75)
    t0 = t16+t46+t47+t50-7.45e+2;
elseif (((t69 & t70) & t72) & t77)
    t0 = t16+t46+t47+t53-1.22e+3;
elseif (((t70 & t73) & t74) & t76)
    t0 = t16+t43+t46+t55-1.22e+3;
elseif (((t68 & t70) & t73) & t75)
    t0 = t16+t43+t46+t50-2.12e+3;
elseif (((t69 & t70) & t73) & t77)
    t0 = t16+t43+t46+t53-2.595e+3;
elseif (((t71 & t72) & t74) & t76)
    t0 = t16+t42+t47+t55-7.45e+2;
elseif (((t68 & t71) & t72) & t75)
    t0 = t16+t42+t47+t50-1.645e+3;
elseif (((t69 & t71) & t72) & t77)
    t0 = t16+t42+t47+t53-2.12e+3;
elseif (((t71 & t73) & t74) & t76)
    t0 = t16+t42+t43+t55-2.12e+3;
elseif (((t68 & t71) & t73) & t75)
    t0 = t16+t42+t43+t50-3.02e+3;
elseif (((t69 & t71) & t73) & t77)
    t0 = t16+t42+t43+t53-3.495e+3;
else
    t0 = NaN;
end
mt1 = [t0];
if ~all(cellfun(@isscalar,{t34,t36,t37,t38,t65,t67,t68,t69,t70,t71,t75,t76,t77}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if ((t37 & t38) & (t67 | t76))
    t0 = t78;
elseif ((t68 & t70) & t75)
    t0 = t81;
elseif ((t37 & t69) & t77)
    t0 = t83;
elseif ((t34 & t38) & (t67 | t76))
    t0 = t78;
elseif ((t65 & t68) & t75)
    t0 = t81;
elseif ((t34 & t69) & t77)
    t0 = t83;
elseif ((t36 & t38) & (t67 | t76))
    t0 = V__v1_0__ps2_1__+t39+t54-1.64e+3;
elseif ((t68 & t71) & t75)
    t0 = V__v1_0__ps2_1__+t39+t49-3.44e+3;
elseif ((t36 & t69) & t77)
    t0 = V__v1_0__ps2_1__+t39+t52-4.39e+3;
else
    t0 = NaN;
end
if ~all(cellfun(@isscalar,{t35,t38,t64,t66,t67,t68,t69,t72,t73,t75,t76,t77}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if ((t66 & ((t38 & t67) | (t35 & t76))) | ((t38 & t72) & t76))
    t1 = t20+t54+2.05e+2;
elseif ((t68 & t72) & t75)
    t1 = t80;
elseif ((t64 & t72) & t77)
    t1 = t82;
elseif ((t66 & t68) & t75)
    t1 = t80;
elseif (t77 & (((t64 & t66) | (t66 & t69)) | (t69 & t72)))
    t1 = t82;
elseif ((t38 & t73) & t76)
    t1 = V__v1_0__ps3_1__+t40+t54-2.545e+3;
elseif ((t68 & t73) & t75)
    t1 = V__v1_0__ps3_1__+t40+t49-4.345e+3;
elseif ((t69 & t73) & t77)
    t1 = V__v1_0__ps3_1__+t40+t52-5.295e+3;
else
    t1 = NaN;
end
mt2 = [t0;t1];
if ~all(cellfun(@isscalar,{t38,t67,t68,t69,t75,t76,t77}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t38 & (t67 | t76))
    t0 = V__v1_0__ps2_1__ps3_1__./1.0e+1+2.1e+2;
elseif (t68 & t75)
    t0 = V__v1_0__ps2_1__ps3_1__+t48-3.39e+3;
elseif (t69 & t77)
    t0 = V__v1_0__ps2_1__ps3_1__+t51-5.29e+3;
else
    t0 = NaN;
end
mt3 = [t0];
if ~all(cellfun(@isscalar,{t68,t69,t70,t71,t72,t73,t74,t75,t76,t77}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (((t70 & t72) & t74) & t76)
    t0 = V__v1_1__+t41+t46+t47+t55+1.55e+2;
elseif (((t68 & t70) & t72) & t75)
    t0 = V__v1_1__+t41+t46+t47+t50-7.45e+2;
elseif (((t69 & t70) & t72) & t77)
    t0 = V__v1_1__+t41+t46+t47+t53-1.22e+3;
elseif (((t70 & t73) & t74) & t76)
    t0 = V__v1_1__+t41+t43+t46+t55-1.22e+3;
elseif (((t68 & t70) & t73) & t75)
    t0 = V__v1_1__+t41+t43+t46+t50-2.12e+3;
elseif (((t69 & t70) & t73) & t77)
    t0 = V__v1_1__+t41+t43+t46+t53-2.595e+3;
elseif (((t71 & t72) & t74) & t76)
    t0 = V__v1_1__+t41+t42+t47+t55-7.45e+2;
elseif (((t68 & t71) & t72) & t75)
    t0 = V__v1_1__+t41+t42+t47+t50-1.645e+3;
elseif (((t69 & t71) & t72) & t77)
    t0 = V__v1_1__+t41+t42+t47+t53-2.12e+3;
elseif (((t71 & t73) & t74) & t76)
    t0 = V__v1_1__+t41+t42+t43+t55-2.12e+3;
elseif (((t68 & t71) & t73) & t75)
    t0 = V__v1_1__+t41+t42+t43+t50-3.02e+3;
elseif (((t69 & t71) & t73) & t77)
    t0 = V__v1_1__+t41+t42+t43+t53-3.495e+3;
else
    t0 = NaN;
end
mt4 = [t0];
if ~all(cellfun(@isscalar,{t34,t36,t37,t38,t65,t67,t68,t69,t70,t71,t75,t76,t77}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if ((t37 & t38) & (t67 | t76))
    t0 = t79;
elseif ((t68 & t70) & t75)
    t0 = t85;
elseif ((t37 & t69) & t77)
    t0 = t87;
elseif ((t34 & t38) & (t67 | t76))
    t0 = t79;
elseif ((t65 & t68) & t75)
    t0 = t85;
elseif ((t34 & t69) & t77)
    t0 = t87;
elseif ((t36 & t38) & (t67 | t76))
    t0 = V__v1_1__ps2_1__+t39+t54-1.64e+3;
elseif ((t68 & t71) & t75)
    t0 = V__v1_1__ps2_1__+t39+t49-3.44e+3;
elseif ((t36 & t69) & t77)
    t0 = V__v1_1__ps2_1__+t39+t52-4.39e+3;
else
    t0 = NaN;
end
if ~all(cellfun(@isscalar,{t35,t38,t64,t66,t67,t68,t69,t72,t73,t75,t76,t77}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if ((t66 & ((t38 & t67) | (t35 & t76))) | ((t38 & t72) & t76))
    t1 = V__v1_1__ps3_1__+t45+t54+2.05e+2;
elseif ((t68 & t72) & t75)
    t1 = t84;
elseif ((t64 & t72) & t77)
    t1 = t86;
elseif ((t66 & t68) & t75)
    t1 = t84;
elseif (t77 & (((t64 & t66) | (t66 & t69)) | (t69 & t72)))
    t1 = t86;
elseif ((t38 & t73) & t76)
    t1 = V__v1_1__ps3_1__+t40+t54-2.545e+3;
elseif ((t68 & t73) & t75)
    t1 = V__v1_1__ps3_1__+t40+t49-4.345e+3;
elseif ((t69 & t73) & t77)
    t1 = V__v1_1__ps3_1__+t40+t52-5.295e+3;
else
    t1 = NaN;
end
mt5 = [t0;t1];
if ~all(cellfun(@isscalar,{t38,t67,t68,t69,t75,t76,t77}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t38 & (t67 | t76))
    t0 = V__v1_0__ps2_1__ps3_1__.*(-9.0./1.0e+1)+V__v1_1__ps2_1__ps3_1__+2.1e+2;
elseif (t68 & t75)
    t0 = V__v1_1__ps2_1__ps3_1__+t48-3.39e+3;
elseif (t69 & t77)
    t0 = V__v1_1__ps2_1__ps3_1__+t51-5.29e+3;
else
    t0 = NaN;
end
mt6 = [t0;V__v1_1__.*(-9.0./4.0e+1)+V__v1_2__-V__v1_1__ps2_1__.*(9.0./4.0e+1)-V__v1_1__ps3_1__.*(9.0./4.0e+1)-V__v1_1__ps2_1__ps3_1__.*(9.0./4.0e+1)+1.55e+2;V__v1_1__ps2_1__.*(-9.0./2.0e+1)+V__v1_2__ps2_1__+t56+1.6e+2;V__v1_1__ps3_1__.*(-9.0./2.0e+1)+V__v1_2__ps3_1__+t56+2.05e+2;V__v1_1__ps2_1__ps3_1__.*(-9.0./1.0e+1)+V__v1_2__ps2_1__ps3_1__+2.1e+2;V__v1_3__-V__v1_2__ps2_1__.*(9.0./4.0e+1)-V__v1_2__ps2_1__ps3_1__.*(9.0./4.0e+1)+t42+t50+1.55e+2;V__v1_2__ps2_1__.*(-9.0./2.0e+1)+V__v1_3__ps2_1__+t57+1.6e+2;V__v1_3__ps3_1__+t49+t57+2.05e+2;V__v1_2__ps2_1__ps3_1__.*(-9.0./1.0e+1)+V__v1_3__ps2_1__ps3_1__+2.1e+2];
mt7 = [V__v1_3__.*(-9.0./4.0e+1)+V__v1_4__-V__v1_3__ps2_1__.*(9.0./4.0e+1)-V__v1_3__ps3_1__.*(9.0./4.0e+1)-V__v1_3__ps2_1__ps3_1__.*(9.0./4.0e+1)+1.55e+2;V__v1_3__ps2_1__.*(-9.0./2.0e+1)+V__v1_4__ps2_1__+t58+1.6e+2;V__v1_3__ps3_1__.*(-9.0./2.0e+1)+V__v1_4__ps3_1__+t58+2.05e+2;V__v1_3__ps2_1__ps3_1__.*(-9.0./1.0e+1)+V__v1_4__ps2_1__ps3_1__+2.1e+2];
diff_exprs_evaluated = [mt1;mt2;mt3;mt4;mt5;mt6;mt7];
end
