function diff_exprs_evaluated = diff_exprs_func_with_policy_state_value(in1)
%DIFF_EXPRS_FUNC_WITH_POLICY_STATE_VALUE
%    DIFF_EXPRS_EVALUATED = DIFF_EXPRS_FUNC_WITH_POLICY_STATE_VALUE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2025/04/16 19:16:42

V__v1_0__ = in1(:,1);
V__v1_1__ = in1(:,5);
V__v1_2__ = in1(:,9);
V__v1_3__ = in1(:,13);
V__v1_4__ = in1(:,17);
V__v1_0__ps2_1__ = in1(:,2);
V__v1_0__ps3_1__ = in1(:,3);
V__v1_1__ps2_1__ = in1(:,6);
V__v1_1__ps3_1__ = in1(:,7);
V__v1_2__ps2_1__ = in1(:,10);
V__v1_2__ps3_1__ = in1(:,11);
V__v1_3__ps2_1__ = in1(:,14);
V__v1_3__ps3_1__ = in1(:,15);
V__v1_4__ps2_1__ = in1(:,18);
V__v1_4__ps3_1__ = in1(:,19);
V__v1_0__ps2_1__ps3_1__ = in1(:,4);
V__v1_1__ps2_1__ps3_1__ = in1(:,8);
V__v1_2__ps2_1__ps3_1__ = in1(:,12);
V__v1_3__ps2_1__ps3_1__ = in1(:,16);
V__v1_4__ps2_1__ps3_1__ = in1(:,20);
diff_exprs_evaluated = [-V__v1_0__+3.495e+3;-V__v1_0__ps2_1__+4.39e+3;-V__v1_0__ps3_1__+5.295e+3;-V__v1_0__ps2_1__ps3_1__+5.29e+3;-V__v1_1__+3.495e+3;-V__v1_1__ps2_1__+4.39e+3;-V__v1_1__ps3_1__+5.295e+3;-V__v1_1__ps2_1__ps3_1__+5.29e+3;-V__v1_2__-1.55e+2;-V__v1_2__ps2_1__-1.6e+2;-V__v1_2__ps3_1__-2.05e+2;-V__v1_2__ps2_1__ps3_1__-2.1e+2;-V__v1_3__-1.55e+2;-V__v1_3__ps2_1__-1.6e+2;-V__v1_3__ps3_1__-2.05e+2;-V__v1_3__ps2_1__ps3_1__-2.1e+2;-V__v1_4__-1.55e+2;-V__v1_4__ps2_1__-1.6e+2;-V__v1_4__ps3_1__-2.05e+2;-V__v1_4__ps2_1__ps3_1__-2.1e+2];
end
